### ISSUE TITLE
32-bit possible?

### ISSUE THREAD

**Issue by v4r4rth** [city96/ComfyUI_ColorMod#2]
Hi, thanks for your efforts! Was just wondering if it was possible to get these images saved as 32-bit with HDR/EXR compression during the encoding! I am currently generating equirectangular images but unable to get the color depth I would like to achieve - hope that is something you can solve? IDK but thanks again :)

**Comment by city96** [comment]
Hi! Started messing with this to see what was possible.

`opencv` has a bunch of functions for HDR/tonemapping so it might be possible to do multiple sampler passes at different brightness levels and then put them together. I'm not sure the output would be a "true" HDR image though. I'll add it tomorrow and see I guess.

It also has stuff for exposure fusion but that doesn't seem that useful considering it's SDR->SDR at that point lol (see: image below)

![tnc](https://github.com/city96/ComfyUI_ColorMod/assets/125218114/3006c5dc-c095-4aa2-a11f-9bdcf5d88650)

**Comment by city96** [comment]
Okay, I've added tonemapping + all the nodes required for HDR. Needs opencv contrib to work so I put that in the `requirements.txt`

Haven't updated the readme yet but you can try them out if you want.

**Comment by richkel** [comment]
this is very interesting and I have been following. How would I implement that picture above?

**Comment by city96** [comment]
@richkel
Late reply but updated the readme + added that specific workflow as an example. It isn't very advanced but should work as a start.
Any comments/insights/etc appreciated. I don't have a 10 bit monitor so checking whether anything useful is happening outside just tonemapping is a bit hard lol.

@v4r4rth 
Also, closing this as complete since technically the implementation is done. Feel free to reopen it if you want something else added.

**Comment by v4r4rth** [comment]
Thanks @city96 I'll check it out once today! I also came across this extension which I'll be trying out with your nodes :)
[https://github.com/spacepxl/ComfyUI-HQ-Image-Save]

**Comment by richkel** [comment]
> Thanks @city96 I'll check it out once today! I also came across this extension which I'll be trying out with your nodes :) https://github.com/spacepxl/ComfyUI-HQ-Image-Save

you should check out this node also it might help you https://github.com/SuperBeastsAI/ComfyUI-SuperBeasts
